// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardLinkController from "./dashboard_link_controller"
application.register("dashboard-link", DashboardLinkController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HeroController from "./hero_controller"
application.register("hero", HeroController)

import MapController from "./map_controller"
application.register("map", MapController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import OfferModalController from "./offer_modal_controller"
application.register("offer-modal", OfferModalController)

import QuoteController from "./quote_controller"
application.register("quote", QuoteController)
