meta_name: "Time 2 Rest"
meta_title: "Time 2 Rest - Trouvez quelqu'un pour prendre soin de votre affaire !"
meta_description: "Time 2 rest est un site de mise en relation entre professionnels independants."
meta_image: "meta-ours.png" # should exist in `app/assets/images/`
